# Generated by Django 4.0.5 on 2022-06-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wolfapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameparameters',
            old_name='preferences',
            new_name='typePreferences',
        ),
        migrations.AddField(
            model_name='gameparameters',
            name='balanceGoal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameparameters',
            name='playerCount',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameparameters',
            name='wolfCount',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
